### ISSUE TITLE
Demande d'ajout d'options au module Mondial Relay

### ISSUE THREAD

**Issue by dev-awevo** [magentix/sylius-mondial-relay-plugin#1]
Bonjour,

Suite à un retour de mon client utilisant votre module, je souhaiterais savoir, s'il serait possible d'ajouter ces deux restrictions aux méthodes de transport Mondial Relay:
- restriction sur certains code postaux
-restriction sur certains produits; si l'un de ces produits est dans le panier, ne pas proposer Mondial Relay (voir pour l'utilisation d'un attribut produit ?)

Merci de me dire, s'il vous est possible de répondre à ces problématiques en modifiant votre module ou si nous devons le faire nous même ?

Cordialement.

**Comment by magentix** [comment]
Bonjour,

Cela concerne t-il le module pour Magento 2?

**Comment by dev-awevo** [comment]
Bonjour,

Oui pour le module Magento 2.

**Comment by magentix** [comment]
Merci de contacter le support du module M2 via le formulaire suivant : 

https://mondialrelay.magentix.fr/magento-2/contact.html

Ce dépôt concerne le module Mondial Relay pour Sylius.
