### ISSUE TITLE
  The table with name 'sylius_dev.sylius_shipment' already exists.  

### ISSUE THREAD

**Issue by Looouuu** [magentix/sylius-mondial-relay-plugin#6]
Hello !

When I install the plugin, I get the message   `The table with name 'sylius_dev.sylius_shipment' already exists. ` after the doctrine:migration:diff.

Any idea ? 

I'm using Sylius 1.8.0-dev.

Thanks a lot !

**Comment by FlorentinGarnier** [comment]
Hello have you found a fix ?

**Comment by Looouuu** [comment]
Nope :(
